//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public Nullable<int> number_of_pets { get; set; }
        public Nullable<int> pet_id { get; set; }
        public string entry_instructions { get; set; }
        public string care_instructions { get; set; }
        public Nullable<System.DateTime> inspection_visit_date { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public System.DateTime created { get; set; }
        public string food { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string service { get; set; }
    }
}
