//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string home_phone { get; set; }
        public string mobile_phone { get; set; }
        public string unit_no { get; set; }
        public string house_no { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postcode { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> last_logged_in { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
    }
}
