//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string review_text { get; set; }
        public int rating { get; set; }
        public System.DateTime created { get; set; }
    }
}
