//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBucket4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> last_logged_in { get; set; }
    }
}
